### ISSUE TITLE
добавить шрифты

### ISSUE THREAD

**Issue by Kumiho1** [Kumiho1/lubimovka#3]

**Comment by elrouss** [comment]
@uzornakovre посмотрел подключение шрифтов к странице - https://github.com/Kumiho1/lubimovka/blob/init/fonts/blocks/page/page.css

Может быть, пропишешь в font-family традиционно также следующие: Arial, Helvetica, sans-serif? Рекомендуется указывать системные шрифты именно **без засечек** на случай проблем с подгрузкой файлов из vendor :))

**Comment by elrouss** [comment]
Проверил
