### ISSUE TITLE
play верстка

### ISSUE THREAD

**Issue by Kumiho1** [Kumiho1/lubimovka#32]

**Comment by Kumiho1** [comment]
- [ ]  создать структуру
- [ ]  прописать css
- [ ]  проверить внешнее соответствие макету
- [ ]  проверить чистоту index.css (чтобы не было тех, кто должен сидеть в папке) 
- [ ]  проверить названия классов, папок, правильную вложенность
- [ ]  по красоте сделал(а)?)

**Comment by sofiapeshekhonova** [comment]
Я бы может добавила  
overflow hidden ?

**Comment by Kumiho1** [comment]
хорошо, в следующем куске работы добавлю)
